In [3]:
import numpy as np
from matplotlib import pyplot as plt
from numpy import sqrt, array, dot

# Vector and Tensor Algebra

### Vectors in different basis

As discussed in the video, in this class we will think of vectors as geometric objects rather than a tuple of numbers. As such, the same vector will have different components depending on the basis we are using. 

Let's say we have agreed on the standard orthonormal basis $\mathbf{e}_i$ and we have the components of a vector $\mathbf{v}$ in that basis, i.e. we know $\mathbf{v}=v_i\mathbf{e}_i$. We will introduce a different orthonormal basis $\mathbf{f}_i$ with known components in the $\mathbf{e}_i$ basis, i.e. we know $\mathbf{f}_j=(f_j)_i\mathbf{e}_i$. The goal is to obtain the components of the vector $\mathbf{v}$ in the new basis $\mathbf{f}_i$. 

As shown in class, because we are talking about the same vector we have 

$$\mathbf{v} = v^{(e_i})_i \mathbf{e}_i = v^{(f_i})_i \mathbf{f}_i$$

where the summation convection has been used (repeated indices denote sum). The transformation of the components of $\mathbf{v}$ can be done as shown in class:

$$
[\mathbf{v}]_{\mathbf{e}} = [\mathbf{Q}][\mathbf{v}]_{\mathbf{f}}
$$

or, equivalently 

$$
[\mathbf{v}]_{\mathbf{f}} = [\mathbf{Q}^T][\mathbf{v}]_{\mathbf{e}}
$$

All we need to clarify is the entries of the matrix $\mathbf{Q}$. As shown in the video, the entries of the matrix $\mathbf{Q}$ are 

$$Q_{ij} = \mathbf{e}_i \cdot \mathbf{f}_j$$ 

Note that we know the components of the basis $\mathbf{f}_j$ in the basis $\mathbf{e}_i$. Thus, we can carry out this products in the basis $\mathbf{e}_i$. As a reminder, the vector $\mathbf{e}_i$ in the basis $\mathbf{e}_i$ is nothing more than the standard basis 

\begin{align}
\mathbf{e}_1 = [1,0,0]_{\mathbf{e}_i}\\
\mathbf{e}_2 = [0,1,0]_{\mathbf{e}_i}\\
\mathbf{e}_3 = [0,0,1]_{\mathbf{e}_i}\\
\end{align}

and remember that in components, the dot product between two vectors $\mathbf{u}$ and $\mathbf{v}$ is 

$$\mathbf{u} \cdot \mathbf{v} = u_i v_i$$ 

as usual. 

In [5]:

# Basis f_j in terms of basis e_i 
f1_e = (1/np.sqrt(2))*np.array([1.,-1.,0])
f2_e = (1/np.sqrt(2))*np.array([1.,1.,0])
f3_e = np.array([0,0,1])

# Basis e_i in terms of basis e_i
e1_e = np.array([1,0,0])
e2_e = np.array([0,1,0])
e3_e = np.array([0,0,1])

# NOTE that in the basis 'f', the vectors f_j are also trivial 
# this is vectors f_j in basis f_j
f1_f = np.array([1,0,0])
f2_f = np.array([0,1,0])
f3_f = np.array([0,0,1])

# We don't know that the basis e_i is in terms of the basis f_i! 

# Note that basis f is orthonormal, we recover the Kronnecker delta f_i dot f_j = delta_ij 
print('\nKronnecker delta from orthonormal basis f')
print(np.dot(f1_e,f1_e))
print(np.dot(f1_e,f2_e))
print(np.dot(f1_e,f3_e))
print(np.dot(f2_e,f1_e))
print(np.dot(f2_e,f2_e))
print(np.dot(f2_e,f3_e))
print(np.dot(f3_e,f1_e))
print(np.dot(f3_e,f2_e))
print(np.dot(f3_e,f3_e))

# It is trivial to see that the dot product of the different e_i vectors also gives you the 
# kronecker delta 

## The transformation matrix between the two basis is done by taking dot products in a given basis
# NOTE: the dot product has to be in the SAME basis 
Q = np.array([[np.dot(e1_e,f1_e),np.dot(e1_e,f2_e),np.dot(e1_e,f3_e)],\
             [np.dot(e2_e,f1_e),np.dot(e2_e,f2_e),np.dot(e2_e,f3_e)],\
             [np.dot(e3_e,f1_e),np.dot(e3_e,f2_e),np.dot(e3_e,f3_e)]])

# Alternative, the components of basis f in terms of basis e defined the matrix Q 
# this is done by basically stacking the vectors 'f' as the columns of Q
Qa = np.stack((f1_e,f2_e,f3_e),axis=1)

# Printing both versions so that you can see that they are equivalent 
print('\nRotation matrix from basis f to basis e (two alternatives, gives the same)')
print(Q)
print(Qa)





Kronnecker delta from orthonormal basis f
0.9999999999999998
0.0
0.0
0.0
0.9999999999999998
0.0
0.0
0.0
1

Rotation matrix from basis f to basis e (two alternatives, gives the same)
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [6]:
# Assume we have a vector v in the ei basis 
v_e = np.array([1.,2.,3])
print('\nComponents of vector v in basis e')
print(v_e)

# With the transformation matrix we can transform components v_e to components v_f 
v_f = np.dot(Q.transpose(),v_e)
print('\nComponents of vector v in basis f')
print(v_f)



Components of vector v in basis e
[1. 2. 3.]

Components of vector v in basis f
[-0.70710678  2.12132034  3.        ]

Components of vector u in basis f
[2 2 2]

Components of vector u in basis e
[2.82842712 0.         2.        ]


**Activity** 

Given a vector in the basis $\mathbf{f}_i$, compute its components in the basis $\mathbf{e}_i$. 
Consider the vector $\mathbf{u}$ which has components $[2,2,2]_{\mathbf{f}_i}$ in the basis $\mathbf{f}_i$. Find the components in the basis $\mathbf{e}_i$. 

In [7]:

# Let's define another vector directly in the basis f
u_f = np.array([2,2,2])
print('\nComponents of vector u in basis f')
print(u_f)

# And get the coordinates of the same vector in basis e 
u_e = np.dot(Q,u_f)
print('\nComponents of vector u in basis e')
print(u_e)


Components of vector u in basis f
[2 2 2]

Components of vector u in basis e
[2.82842712 0.         2.        ]


I cannot stress enough that we are talking about the same vectors, imagine these vectors as arrows in space. When we pick the three special vectors $\mathbf{e}_i$ we can express all vectors in terms of this basis, including other basis vectors. Similarly, if we have some other vectors $\mathbf{f}_i$ and we pick them as basis then we can put all other vectors in terms of the $\mathbf{f}_i$ basis.  

In many of the examples later in class we will not actually keep track of the basis because it will be implied that we just use the same basis all the time and in that case one can skip the notation. However, for this module it is important to get familiar with change of basis. 

### Invariants for vectors: dot product 

Invariants are quantities that do not change when we change basis. For vectors, it all comes from the dot product. 
If you think of vectors as geometric objects then you will see that all we need to be able to measure for vectors are lengths and angles. These quantities should not depend on the basis. These quantities are at the center of the definition of the dot product. That's why the dot product should not change when we change basis. So, if in a given basis we have 

$$\alpha = \mathbf{v}\cdot \mathbf{u} = v_i u_i$$

Then we we change basis we will get new components, call them $v'_i, u'_i$, the dot product should be the same 

$$\alpha = \mathbf{v}\cdot \mathbf{u} = v'_i u'_i$$

**Activity**

* Fill out the code below to compute the dot product of two vectors in two different basis and check that you get the same result, i.e. that the dot product is invariant under coordinate transformation
* Use the dot product to compute the length of a vector by doing the dot product with itself and taking sqrt 

In [29]:
# And let's check that the dot product is invariant! 
# Dot product in the basis e
u_dot_v_in_e = u_e[0]*v_e[0]+u_e[1]*v_e[1]+u_e[2]*v_e[2]
# Dot product in the basis f
u_dot_v_in_f = u_f[0]*v_f[0]+u_f[1]*v_f[1]+u_f[2]*v_f[2]
print('u dot v in basis e = %f'%u_dot_v_in_e)
print('u dot v in basis f = %f'%u_dot_v_in_f)


u dot v in basis e = 8.828427
u dot v in basis f = 8.828427

Cross product with Levi Civita in e
[-4.         -6.48528137  5.65685425]
Cross product with Levi Civita in f transformed to e using Q
[-4.         -6.48528137  5.65685425]
Cross product with numpy
[-4.         -6.48528137  5.65685425]


### Cross product

While not as generally used as the dot product, the cross product is useful to define a vector that is normal to two other vectors. The definition is in the video and here we just show a simple example. Importantly, the cross product is also a *geometric* operation. That is, it should not matter which basis we use to compute the cross product we should get the same result. 

In [8]:

# How about the cross product? Remember the indicial definition of the cross product 
# We need the definition of the Levi-Civita symbol
def epsilon(i,j,k):
    if i==1 and j==2 and k==3:
        return 1
    if i==2 and j==3 and k==1:
        return 1
    if i==3 and j==1 and k==2:
        return 1
    if i==1 and j==3 and k==2:
        return -1
    if i==2 and j==1 and k==3:
        return -1
    if i==3 and j==2 and k==1:
        return -1
    return 0

w_e = np.zeros((3))
w_f = np.zeros((3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            # careful with indexing, in these loops i,j,k take the values 0,1,2
            # but the function defined above for epsilon expects 1,2,3
            w_e[i] += epsilon(i+1,j+1,k+1)*u_e[j]*v_e[k]
            w_f[i] += epsilon(i+1,j+1,k+1)*u_f[j]*v_f[k]

# to compare we need to switch coordinates to one of the two
w_e_Q = np.dot(Q,w_f)
# and for checking let's ask numpy to do it as well 
w_e_np = np.cross(u_e,v_e)
print('\nCross product with Levi Civita in e')
print(w_e)
print('Cross product with Levi Civita in f transformed to e using Q')
print(w_e_Q)
print('Cross product with numpy')
print(w_e_np)

# NOTE. The cross product depends on the right-hand rule, so cross products calculated in e_i basis or
# f_i basis will be the same as long as the e_i basis has the same handness as the basis f! otherwise there
# will be a -1 different between the two from the change in handness. Just to keep in mind


Cross product with Levi Civita in e
[-4.         -6.48528137  5.65685425]
Cross product with Levi Civita in f transformed to e using Q
[-4.         -6.48528137  5.65685425]
Cross product with numpy
[-4.         -6.48528137  5.65685425]


### Second order tensors in different basis and invariants 

Remember that now, given the basis $\mathbf{e}_i$ for vectors, there is a natural basis for second order tensors $\mathbf{e}_i\otimes \mathbf{e}_j$, such that we can represent a second order tensor $\mathbf{A}$ with a matrix

$$
\mathbf{A} = A_{ij}\mathbf{e}_i\otimes\mathbf{e}_j
$$ 

Given another basis for vectors $\mathbf{f}_i$, and the corresponding basis for tensors $\mathbf{f}_i\otimes \mathbf{f}_j$, the components of the same tensor $\mathbf{A}$ in this new basis can be obtained by 

$$
[\mathbf{A}]_{\mathbf{e}\otimes\mathbf{e}}= [\mathbf{Q}][\mathbf{A}]_{\mathbf{f}\otimes\mathbf{f}}[\mathbf{Q}^T]
$$

Or

$$
[\mathbf{A}]_{\mathbf{f}\otimes\mathbf{f}}= [\mathbf{Q}^T][\mathbf{A}]_{\mathbf{e}\otimes\mathbf{e}}[\mathbf{Q}]
$$

In [46]:
# second order tensor A in matrix e dyad e
A_ee = np.array([[1,2,3],[3,2,1],[3,1,2]])

# Transform to basis f dyad f
A_ff = np.dot(Q.transpose(),np.dot(A_ee,Q))

# second order tensor A in matrix f dyad f
B_ff = np.array([[2,2,2],[1,2,2],[1,1,2]])

# Transform to basis e dyad e
B_ee = np.dot(Q,np.dot(B_ff,Q.transpose()))

print('A_ee')
print(A_ee)
print('A_ff')
print(A_ff)
print('\nB_ee')
print(B_ee)
print('B_ff')
print(B_ff)

# Now the interesting part, Invariants! 
# first the new dot product we defined for second order tensors A:B 
print('\nInavriants')

def A_dotdot_B(A,B):
    sum = 0
    for i in range(3):
        for j in range(3):
            sum+= A[i,j]*B[i,j]
    return sum

A_dd_B_in_e = A_dotdot_B(A_ee,B_ee)
A_dd_B_in_f = A_dotdot_B(A_ff,B_ff)
print('\nA:B calculated in basis e dyad e: %f'%A_dd_B_in_e)
print('A:B calculated in basis f dyad f: %f'%A_dd_B_in_f)

# Now the three invariants we defined

# first invariant is the trace of A, sum of diagonal entries 
A_I1_in_e = A_ee[0,0] + A_ee[1,1] + A_ee[2,2]
# an alternative way of defining it 
Identity = np.eye(3)
A_I1_in_f = A_dotdot_B(A_ee,Identity)
print('\nI1 of A in basis e dyad e: %f'%A_I1_in_e)
print('I1 of A in basis f dyad f: %f'%A_I1_in_f)

# second invariant is 0.5*(trA^2-tr(A^2))
A_I2_in_e = 0.5*(A_I1_in_e**2 - A_dotdot_B(np.dot(A_ee,A_ee),Identity))
# alternative definition from the fact that tr(A^2) = A^T:A 
A_I2_in_f = 0.5*(A_I1_in_f**2 - A_dotdot_B(A_ff.transpose(),A_ff))
print('\nI2 of A in basis e dyad e: %f'%A_I2_in_e)
print('I2 of A in basis f dyad f: %f'%A_I2_in_f)

# third invariant 
A_I3_in_e = np.linalg.det(A_ee)
# in f, alternative definition using the Levi Civita symbol! det(A) = epsilon_ijk A_1i A_2j A_3k
A_I3_in_f = 0
for i in range(3):
    for j in range(3):
        for k in range(3):
            A_I3_in_f+=epsilon(i+1,j+1,k+1)*A_ff[0,i]*A_ff[1,j]*A_ff[2,k]
print('\nI3 of A in basis e dyad e: %f'%A_I3_in_e)
print('I3 of A in basis f dyad f: %f'%A_I3_in_f)

A_ee
[[1 2 3]
 [3 2 1]
 [3 1 2]]
A_ff
[[-1.         -1.          1.41421356]
 [ 0.          4.          2.82842712]
 [ 1.41421356  2.82842712  2.        ]]

B_ee
[[ 3.5         0.5         2.82842712]
 [-0.5         0.5         0.        ]
 [ 1.41421356  0.          2.        ]]
B_ff
[[2 2 2]
 [1 2 2]
 [1 1 2]]

Inavriants

A:B calculated in basis e dyad e: 20.727922
A:B calculated in basis f dyad f: 20.727922

I1 of A in basis e dyad e: 5.000000
I1 of A in basis f dyad f: 5.000000

I2 of A in basis e dyad e: -8.000000
I2 of A in basis f dyad f: -8.000000

I3 of A in basis e dyad e: -12.000000
I3 of A in basis f dyad f: -12.000000


### Fourth order tensors

In [58]:
# We will have more opportunities of dealing with 4th order tensors, but for now lets just define the double
# contraction 

def CC_dotdot_A(CC,A):
    B = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            for k in range(3):
                for l in range(3):
                    B[i,j] += CC[i,j,k,l]*A[k,l]
    return B

# Definining a fourth order tensor, has 4 indices! 
# maybe difficult to visualize, it has 81 entries!!! 
CC_ee = np.zeros((3,3,3,3))
# I will fill it in a way that makes it better to imagine... 
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                CC_ee[i,j,k,l] = i*3+j
print('fourth order tensor CC has 81 entries, I filled it in with a pattern...')
print(CC_ee)

# Let's just aply this fourth order tensor to a second order tensor, i get back another second order tensor
D = CC_dotdot_A(CC_ee,A_ee)
print('\nsecond order tensor from applyng a 4th order tensor to a 2nd order tensor CC:A')
print(D)

fourth order tensor CC has 81 entries, I filled it in with a pattern...
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]]


 [[[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[4. 4. 4.]
   [4. 4. 4.]
   [4. 4. 4.]]

  [[5. 5. 5.]
   [5. 5. 5.]
   [5. 5. 5.]]]


 [[[6. 6. 6.]
   [6. 6. 6.]
   [6. 6. 6.]]

  [[7. 7. 7.]
   [7. 7. 7.]
   [7. 7. 7.]]

  [[8. 8. 8.]
   [8. 8. 8.]
   [8. 8. 8.]]]]

second order tensor from applyng a 4th order tensor to a 2nd order tensor CC:A
[[  0.  18.  36.]
 [ 54.  72.  90.]
 [108. 126. 144.]]


In [ ]:
#### 

# Second order tensor A with components in the ei dyad ej basis

Af = np.array([[1,2,3],[2,3,2],[3,3,1]])

# I want components in basis ei dyad ej 

Ae = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                Ae[l,k] = Ae[l,k] + Af[i,j]*Q[k,j]*Q[l,i]

                
Ae = np.dot(Q,np.dot(Af,Q.transpose()))

